Repository plone/plone.app.upgrade, pull requests merged in 2019-02, with the labels that each got.

#185 Plip 2516 navigation
  plone/app/upgrade/v52/alphas.py
  plone/app/upgrade/v52/betas.py
  plone/app/upgrade/v52/configure.zcml
  plone/app/upgrade/v52/profiles.zcml
  plone/app/upgrade/v52/profiles/to_alpha1/.gitkeep
  plone/app/upgrade/v52/profiles/to_beta1/registry.xml
  plone/app/upgrade/v52/profiles/to_beta1/repositorytool.xml
Labels: 03 type: feature (plip), 24 status: ready

#184 PLIP 1653 - Restructure static resources
  news/184.news
  plone/app/upgrade/v52/profiles/to_beta1/registry.xml
Labels: 03 type: feature (plip), 24 status: ready

#195 Remove interface indexes from relation catalog
  news/195.bugfix
  plone/app/upgrade/v52/betas.py
Labels: 01 type: bug, 23 status: testing

#196 Added URL Management controlpanel and object_button action.
  news/1486.feature
  plone/app/upgrade/v52/profiles/to_beta1/actions.xml
  plone/app/upgrade/v52/profiles/to_beta1/controlpanel.xml
  plone/app/upgrade/v52/profiles/to_beta1/rolemap.xml
  plone/app/upgrade/v52/profiles/to_beta1/toolset.xml
Labels: 03 type: feature (plip), 23 status: testing

#198 Fixed permission error while removing old resource registries.
  news/197.bugfix
  plone/app/upgrade/v52/betas.py
Labels: 01 type: bug, 12 prio: high, 23 status: testing, 32 needs: review

#200 add bbb for CSSRegistryTool and JSRegistryTool
  news/200.bugfix
  plone/app/upgrade/__init__.py
  plone/app/upgrade/bbb.py
Labels: 24 status: ready
