Repository plone/plone.app.upgrade, pull requests merged in 2020-09, with the labels that each got.

#238 Fixed deprecation warning for zope.site.hooks.
  news/3130.bugfix
  plone/app/upgrade/tests/base.py
Labels: 01 type: bug, 14 prio: low, 23 status: testing

#239 Plone 5.1.7: Update resource registry last_compilation date.
  news/1006.bugfix
  plone/app/upgrade/v51/profiles/to_517/registry.xml
Labels: 04 type: enhancement, 11 prio: blocker, 24 status: ready, 32 needs: review

#240 Migrate the plone.site_logo field from ASCII (native string) to Bytes.
  news/3172.bugfix
  plone/app/upgrade/v52/configure.zcml
  plone/app/upgrade/v52/final.py
  plone/app/upgrade/v52/tests.py
Labels: 02 type: regression, 13 prio: normal, 22 status: in-progress, 32 needs: review

#243 Fixed invalid escape sequence.
  news/3130.bugfix
  plone/app/upgrade/v43/alphas.py
Labels: 01 type: bug, 14 prio: low, 23 status: testing

#242 Replaced import of plone.api, which should not be used by core.
  news/241.bugfix
  plone/app/upgrade/v52/final.py
Labels: 02 type: regression, 12 prio: high, 23 status: testing, 32 needs: review

#244 fix edge case, where relations attributes are missing in catalog
  news/244.bugfix
  plone/app/upgrade/v52/betas.py
Labels: 04 type: enhancement, 13 prio: normal, 23 status: testing
